steps:
  - id: 'docker build'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE', '.']

  - id: 'docker push'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE']

  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - cd terraform && terraform init

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - cd terraform && terraform plan -var image=${_IMAGE}

  - id: 'tf fmt'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - cd terraform && terraform fmt -check

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    args:
    - '-c'
    - cd terraform && terraform apply -auto-approve -var image=${_IMAGE}

substitutions:
  _IMAGE: gcr.io/${PROJECT_ID}/${REPO_NAME}:${SHORT_SHA}

options:
  logging: CLOUD_LOGGING_ONLY
