name: Deploy to Cloud Run
on: [push]
defaults:
      run:
        shell: bash

permissions:
      contents: 'read'
      id-token: 'write'

env:
  IMAGE: us-central1-docker.pkg.dev/smart-envoy-270916/my-docker-repo/helloworld
  SERVICE_ACCOUNT: my-service-account@smart-envoy-270916.iam.gserviceaccount.com
  WIF_POOL: projects/952063690068/locations/global/workloadIdentityPools/wif-pool/providers/gh-provider

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: $WIF_POOL
            service_account: $SERVICE_ACCOUNT

      - id: 'build'
        run: |
          echo yes | gcloud auth configure-docker us-central1-docker.pkg.dev
          TAGGED_IMAGE=$IMAGE:$(git rev-parse --short HEAD)
          docker build -t $TAGGED_IMAGE .
          docker push $TAGGED_IMAGE
          echo "BUILT_IMAGE=$TAGGED_IMAGE" >> $GITHUB_OUTPUT

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'cloudrun-gha'
          image: ${{ steps.build.BUILT_IMAGE }}
