name: Deploy to Cloud Run with Terraform
on: [push]
defaults:
  run:
    shell: bash

permissions:
  contents: 'read'
  id-token: 'write'

env:
  IMAGE: us-central1-docker.pkg.dev/smart-envoy-270916/my-docker-repo/helloworld
  SERVICE_ACCOUNT: my-service-account@smart-envoy-270916.iam.gserviceaccount.com
  WIF_POOL: projects/952063690068/locations/global/workloadIdentityPools/wif-pool/providers/gh-provider

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: ${{ env.WIF_POOL }}
            service_account: ${{ env.SERVICE_ACCOUNT }}

      - id: 'build'
        run: |
          echo yes | gcloud auth configure-docker us-central1-docker.pkg.dev
          TAGGED_IMAGE=$IMAGE:$(git rev-parse --short HEAD)
          docker build -t $TAGGED_IMAGE .
          docker push $TAGGED_IMAGE
          echo "BUILT_IMAGE=$TAGGED_IMAGE" >> $GITHUB_OUTPUT

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: ${{ env.WIF_POOL }}
            service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: 'Terraform Plan'
        run: terraform plan -var image="$IMAGE:$(git rev-parse --short HEAD)"

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve -var image="$IMAGE:$(git rev-parse --short HEAD)"
