name: Cloud Deploy (prod)

on:
  push:
    tags:
      - v1.**

defaults:
  run:
    shell: bash

permissions:
  contents: 'read'
  id-token: 'write'

env:
  PROJECT_ID: smart-envoy-270916
  REGION: us-central1
  DELIVERY_PIPELINE: helloworld-app-pipeline
  PROD_TARGET: cloudrun-prod-target
  SERVICE_ACCOUNT: my-service-account@smart-envoy-270916.iam.gserviceaccount.com
  WIF_POOL: projects/952063690068/locations/global/workloadIdentityPools/wif-pool/providers/gh-provider

jobs:
  release-prod:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
            workload_identity_provider: ${{ env.WIF_POOL }}
            service_account: ${{ env.SERVICE_ACCOUNT }}

      - id: 'promote'
        name: 'Promote dev release to prod'
        run: |
          echo "Deploying $(git describe --tags --abbrev=0)"
          gcloud deploy releases promote \
            --release=release-$(git rev-parse --short HEAD) \
            --delivery-pipeline=$DELIVERY_PIPELINE \
            --project=$PROJECT_ID \
            --region=$REGION \
            --to-target=$PROD_TARGET
